### ISSUE TITLE
CMake build does not allow more than one flag to be specified for option -Dwith-optimize=flag1;flag2; ...

### ISSUE THREAD

**Issue by gtrensch** [nest/nest-gpu#51]
The CMake build does not allow more than one flag to be specified for option -Dwich-optimize=op1;op2 ...
The problem is addressed in NEST issue [2584](https://github.com/nest/nest-simulator/issues/2548) and PR [2551](https://github.com/nest/nest-simulator/pull/2551).

**Comment by JoseJVS** [comment]
A fix is already included in #45
