### ISSUE TITLE
Port existing documentation to readthedocs

### ISSUE THREAD

**Issue by jhnnsnk** [nest/nest-gpu#9]
The documentation of NEST GPU is currently still in the [Wiki](https://github.com/golosio/NeuronGPU/wiki) of the former repository.
As a first step towards aligning the documentation to that of the [NEST Simulator](https://nest-simulator.readthedocs.io), I would suggest to bring the existing documentation to readthedocs.

**Comment by jessica-mitchell** [comment]
@jhnnsnk I am happy to help with documentation for this project - but for Read the docs setup, someone with admin rights to the project needs to do it (At least help with the initial setup).

**Comment by gmtiddia** [comment]
@jessica-mitchell I can help porting the documentation to Read the docs. How can I help?

**Comment by jessica-mitchell** [comment]
I think the intiai steps have been achieved for this issue; an y additional documentation related topics should have their own issue. Closing.
